argc_argv

diff --git a/helper b/helper
--- a/helper
+++ b/helper
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 # Directory where the files are located
-DIR_PATH="recursion"
+DIR_PATH="argc_argv"
 TEST_DIR="tests"
 BUILD_DIR="$TEST_DIR/build"
 
@@ -19,19 +19,24 @@ compile_and_check() {
 
     if [ $? -eq 0 ]; then
         echo "Betty successfully"
-        echo "Compiling test file($TEST_FILE) ..."
 
-        # Compile the Unity test file
-        gcc -Wall -Werror -Wextra -pedantic -std=gnu89 \
-            "$TEST_DIR/_putchar.c" "$FILE_PATH" "$TEST_FILE" -o "$BUILD_DIR/test_${TEST_FILE_BASE%.c}" \
-            -I "$TEST_DIR/Unity/src" -L "$TEST_DIR/Unity/build" -lunity -D__CUSTOM_DEBUG__=1
-
-         if [ $? -eq 0 ]; then
-            echo "Running tests..."
-            ./"$BUILD_DIR/test_${TEST_FILE_BASE%.c}"
+        if [ $2 == "notest" ]; then
+            echo "Compiling file($FILE_PATH)..."
         else
-            echo "Test compilation failed."
-            exit 1
+            echo "Compiling test file($TEST_FILE) ..."
+
+            # Compile the Unity test file
+            gcc -Wall -Werror -Wextra -pedantic -std=gnu89 \
+                "$TEST_DIR/_putchar.c" "$FILE_PATH" "$TEST_FILE" -o "$BUILD_DIR/test_${TEST_FILE_BASE%.c}" \
+                -I "$TEST_DIR/Unity/src" -L "$TEST_DIR/Unity/build" -lunity -D__CUSTOM_DEBUG__=1
+
+                if [ $? -eq 0 ]; then
+                echo "Running tests..."
+                ./"$BUILD_DIR/test_${TEST_FILE_BASE%.c}"
+            else
+                echo "Test compilation failed."
+                exit 1
+            fi
         fi
     fi
 }
